apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dev-calendar
  namespace: app
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: dev-calendar.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dev-calendar
                port:
                  number: 80

