apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
namePrefix: dev-
resources:
  - ../../base
images:
  - name: app
    newName: ghcr.io/seokheounjo/dev-calendar
    newTag: latest
patches:
  - target:
      kind: Deployment
      name: dev-calendar
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Namespace
      name: app
    patch: |-
      - op: replace
        path: /metadata/name
        value: dev
  - target:
      kind: Ingress
      name: dev-calendar
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: dev.dev-calendar.local

